name: Manually trigger an Azure Machine Learning job

on: [push]

permissions:
  id-token: write

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    # Debug Step: Show the current authenticated Azure identity
    - name: Check Azure identity
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          echo "Checking Azure identity..."
          az account show
  
    - name: List compute instances
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          echo "Listing available compute instances..."
          az ml compute list --workspace-name azure-ml --resource-group ml-course
  
    - name: Show compute instance details
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          echo "Showing details for the compute instance..."
          az ml compute show --name ml-vm --workspace-name azure-ml --resource-group ml-course
  
    - name: Trigger Azure ML job
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          echo "Triggering Azure ML job..."
          az ml job create --file src/job.yml --resource-group ml-course --workspace-name azure-ml
