name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Trigger Azure ML job
      uses: azure/azure-ml-sdk-action@v1
      with:
        resource-group: ml-course
        workspace-name: azure-ml
        job-file: src/job.yml
