name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Debug Step: Show the current authenticated Azure identity
    - name: Check Azure identity
      run: |
        echo "Checking Azure identity..."
        az account show

    # Debug Step: List available compute instances in the workspace
    - name: List compute instances
      run: |
        echo "Listing available compute instances..."
        az ml compute list --workspace-name azure-ml --resource-group ml-course

    # Debug Step: Show details of the specific compute instance (replace <your-compute-instance> with actual name)
    - name: Show compute instance details
      run: |
        echo "Showing details for the compute instance..."
        az ml compute show --name ml-vm --workspace-name azure-ml --resource-group ml-course

    - name: Trigger Azure ML job
      run: |
        echo "Triggering Azure ML job..."
        az ml job create --file src/job.yml --resource-group ml-course --workspace-name azure-ml --compute-target ml-vm
